# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Playwright tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: 
    # nightly
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Build build
      run: npm run build:testlib
    - name: Run your tests
      run: npm run playwright_test
      env:
        ILEFTIT_SECRET: ${{ secrets.ILEFTIT_SECRET }}
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        AZURE_STORAGE_CONTAINER_NAME: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
        AZURE_STORAGE_LOG_TABLE_NAME: ${{ secrets.AZURE_STORAGE_LOG_TABLE_NAME }}
    